### ISSUE TITLE
Is the drag and drop feature included?

### ISSUE THREAD

**Issue by m-taha52** [dheerajshenoy/cometfm#1]
The windows file manager contains a drag and drop feature that allows you to copy and paste files between directories by dragging them across folders 

Can I do that here?

**Comment by dheerajshenoy** [comment]
Not yet. It will be added soon. Other changes have been done, please check the `README.org` file.

**Comment by dheerajshenoy** [comment]
Along with drag and drop support many other things have been added. Please refer to the TODO.org file in the repository's main page
